accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
#    path("login",views.login, name="login")
    path("register/", views.register, name="register"),
]

chat/urls.py
from django.urls import path
from . import views


app_name = "chat"

urlpatterns = [
    path("", views.index, name="index"),
    path("<int:room_id>/", views.room, name="room"),
    path("createRoom/", views.create_room, name="createRoom"),
]

chatapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('chat/', include('chat.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include("django.contrib.auth.urls")),
    path('friends/', include('friends.urls')),
]

friends/urls.py
from django.urls import path
from . import views

urlpatterns = [
        path("find/<str:query>", views.find_friend, name="find-friend"),
        path("add/<str:username>", views.add_friend, name="add-friend"),

]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    friends = models.ManyToManyField("self",symmetrical=True)

# Create your models here.

chat/models.py
from django.db import models
from accounts.models import User
# Create your models here.


class Room(models.Model):
    users = models.ManyToManyField(User, related_name='rooms')   
    name = models.CharField(max_length=100, null=True)
    def __str__(self):
        return f'{self.name}'


class Message(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE, related_name='messages')
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return f'{self.sender}: {self.content}'

friends/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django.contrib.auth.forms import BaseUserCreationForm
from django.contrib.auth import get_user_model

class RegisterForm(BaseUserCreationForm):
    class Meta(BaseUserCreationForm.Meta):
        model = get_user_model()

accounts/views.py
from django.shortcuts import render, redirect
from .forms import RegisterForm
from django.contrib import messages

# Create your views here.
def login(request):
    return render(request, "accounts/login.html")

def register(request):
    if request.method == 'POST':
        form =  RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.INFO, "Created Account, Now you can login")
            return redirect("/accounts/login")
    else:
        form = RegisterForm()
    return render(request, "registration/register.html",{"form":form})

chat/views.py
from django.shortcuts import render, redirect
from .models import Message, Room
from django.db.models import Max, Field
from django.contrib.auth.decorators import login_required
from .room_managment import create_room_obj
from django.http import HttpResponse
from django.contrib.auth import get_user_model
import json
# Create your views here.


@login_required
def index(request):
    latest_room_id = sort_rooms_latest_message(request.user)[0].id
    room_url = "/chat/"+str(latest_room_id)
    return redirect(room_url)


@login_required
def room(request, room_id):
    room = Room.objects.get(id=room_id)
    if not room.users.filter(id=request.user.id).exists():
        latest_room_id = sort_rooms_latest_message(request.user)[0].id
        room_url = "/chat/"+str(latest_room_id)
        return redirect(room_url)

    room.name = set_room_name(room, request.user)
    latest_messages = room.messages.order_by("timestamp")[:10]
    return render(request, "chat/index.html", {
        "current_room": room,
        "latest_messages": latest_messages,
        "sorted_rooms": sort_rooms_latest_message(request.user)
        })


@login_required
def create_room(request):
    if request.method == 'POST':
        User = get_user_model()
        room_creator = request.user

        data = json.loads(request.body.decode('utf-8'))
        users = data['users']
        group_name = data['group_name']
        users = list(map(lambda user: User.objects.get(username=user), users))
        users.append(room_creator)

        create_room_obj(users, group_name)
        print(users)
    return HttpResponse(status=200)


def sort_rooms_latest_message(user):
    rooms = user.rooms.all()

    for room in rooms:
        last_message = room.messages.order_by('-timestamp').first()
        if last_message:
            last_message.content = cut_text(last_message.content, 10)
        room.last_message = last_message
        room.name = set_room_name(room, user)
    return rooms


def cut_text(text, max_lenght):
    shorted = text[:max_lenght]
    if len(text) > max_lenght:
        shorted = shorted + "..."
    return shorted


def set_room_name(room, current_user):
    name = room.name
    if room.name is None:
        usernames = room.users.all().exclude(id=current_user.id).values_list("username", flat=True)
        name = ", ".join(usernames)
    return name

friends/views.py
from django.shortcuts import render
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from chat.room_managment import create_room_obj
# Create your views here.
@login_required
def find_friend(request, query):
    User = get_user_model()
    user = request.user

    result = User.objects.filter(username__icontains=query).exclude(username=user.username)[:5]
    print(result)
    return render(request, "friends/add-friend.html",{"friends_results":result})

@login_required
def add_friend(request, username):
    if request.method == 'POST':
        User = get_user_model()
        user = request.user
        friend = User.objects.get(username=username)

        user.friends.add(friend)
        user.save()
        create_room_obj([user, friend])

    return redirect("/chat/index/")

templates/accounts/login.html
<!-- chat/templates/accounts/login.html -->
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Login</title>
</head>
<body>
    <form id="loginForm">
        <label for="login">Login: </label><br/>
        <input type="text" name="login" id="login"/><br/>

        <label for="password">Password: </label><br/>
        <input type="password" name="password" id="password"/><br/>

        <button id="loginButton">Login</button>
    </form>
    

    <script>
        document.getElementById("loginForm").addEventListener("submit", async function(e){
            e.preventDefault();
            
            const login = document.getElementById("login").value
            const password = document.getElementById("password").value
            
            const response = await fetch("http://0.0.0.0:8000/login",{
                method: "POST",
                body: JSON.stringify({ login: login, password: password})
            })

        }) 
    </script>

</body>
</html>

templates/chat/create-group-modal-record.html
<div class="space-y-2">
  <div class="flex items-center justify-between p-3 rounded-lg border border-[#232323] cursor-pointer transition-colors hover:bg-black/5">
    <div class="flex items-center gap-3">
      <div class="relative">
          {% include "chat/icons/user-logo.html" with username=username  %}
          <div class="absolute -bottom-1 -right-1 w-3 h-3 rounded-full border-2 border-white bg-[#f45d48]"></div>
      </div>
      <div>
          <p class="font-medium text-[#232323]">{{username}}</p>
      </div>
    </div>
    <input type="checkbox" data-username="{{ username }}" class="modal-create-group-friend-record-checbox w-5 h-5 rounded border-2 border-[#232323] hover:cursor-pointer"></input>
  </div>

templates/chat/create-group-modal.html
<!-- <div id="modal-create-group" class="fixed inset-0 hidden bg-black bg-opacity-50 flex items-center justify-center z-50">
    <h3>Create Group</h3>
    <div id="modal-create-group-user-friends">
    {% for friend in request.user.friends.all %}
        {% include "chat/create-group-modal-record.html" with username=friend.username %}
    {% endfor %}
    </div>
    <button id="modal-create-group-button-submit" data-username="{{ username }}">Create Group</button>
</div> -->



<div class="fixed inset-0 bg-black/50 flex items-center justify-center z-50 animate-in fade-in duration-200">
  <div data-slot="card" class="bg-white text-[#232323] flex flex-col gap-6 rounded-xl py-6 shadow-sm w-full max-w-lg border border-[#232323] animate-in zoom-in-95 duration-200">
    
    <!-- Header -->
    <div class="p-6 border-b border-[#232323]">
      <div class="flex items-center justify-between mb-4">
        <h3 class="text-lg font-semibold text-[#232323]">Create Group Chat</h3>
        <button id="add-group-close-modal" class="inline-flex items-center justify-center rounded-md size-9 text-sm font-medium text-[#232323] hover:bg-accent hover:text-accent-foreground disabled:opacity-50">
            {% include "chat/icons/close-icon.html" %}
        </button>
      </div>

      <div class="space-y-4">
        <div>
          <label class="text-sm font-medium text-[#232323]">Group Name</label>
          <input id="create-group-name" placeholder="Enter group name" value=""
            class="mt-1 w-full rounded-md border border-[#232323] bg-[#f8f5f2] px-3 py-1 text-base text-[#222525] shadow-xs focus-visible:ring-2 focus-visible:ring-ring/50 h-9" />
        </div>
      </div>
    </div>

    <!-- Members -->
    <div class="p-6 max-h-80 overflow-y-auto">
      <div class="space-y-4">
        <div>
          <label class="text-sm font-medium text-[#232323]">Add Members</label>
          <div class="relative mt-1">
            {% include "chat/icons/maginfire-icon.html" %}
            <input placeholder="Search friends to add" value=""
              class="pl-10 w-full rounded-md border border-[#232323] bg-[#f8f5f2] px-3 py-1 text-base text-[#222525] shadow-xs h-9" />
          </div>
        </div>
            {% for friend in request.user.friends.all %}
                {% include "chat/create-group-modal-record.html" with username=friend.username %}
            {% endfor %}

        </div>
      </div>
    </div>

    <!-- Footer -->
    <div class="p-6 border-t border-[#232323]">
      <div class="flex gap-2">
        <button id="modal-create-group-button-submit"
          class="flex-1 rounded-md border border-[#232323] bg-transparent text-[#232323] px-4 py-2 h-9 text-sm font-medium shadow-xs hover:bg-[#078080] hover:cursor-pointer">
          Create Group
        </button>
        <button id="modal-create-group-cancel" class="flex-1 rounded-md border border-[#232323] bg-transparent text-[#232323] px-4 py-2 h-9 text-sm font-medium shadow-xs hover:bg-[#F45D48] hover:cursor-pointer">
        Cancel
        </button>



<script>
    const requestUrl = '{% url 'chat:createRoom' %}'
        const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
        document.getElementById('modal-create-group-button-submit').addEventListener('click' , async function(e) {
            const checked = document.querySelectorAll('.modal-create-group-friend-record-checbox:checked');
            const values = Array.from(checked).map( checkbox => checkbox.dataset.username);
            const groupName = document.getElementById('create-group-name').value;
            

            try {
                const response = await fetch(requestUrl,{
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                        'X-CSRFToken': csrftoken
                    },
                    body: JSON.stringify({ users: values, group_name: groupName })
                });
                if (!response.ok) {
                    throw new Error(`Response status: ${response.status}`);
                }else {
                    //Message: Room created sucesfully
                    window.location.href = '/chat/';
                }
            } catch (error) {
                console.error(error.message);
            }

        });

</script>

templates/chat/icons/add-friend-icon.html
<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.25" stroke="currentColor" class="size-6">
  <path stroke-linecap="round" stroke-linejoin="round" d="M18 7.5v3m0 0v3m0-3h3m-3 0h-3m-2.25-4.125a3.375 3.375 0 1 1-6.75 0 3.375 3.375 0 0 1 6.75 0ZM3 19.235v-.11a6.375 6.375 0 0 1 12.75 0v.109A12.318 12.318 0 0 1 9.374 21c-2.331 0-4.512-.645-6.374-1.766Z" />
</svg>

templates/chat/icons/add-group-icon.html
<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.25" stroke="currentColor" class="size-6">
  <path stroke-linecap="round" stroke-linejoin="round" d="M18 18.72a9.094 9.094 0 0 0 3.741-.479 3 3 0 0 0-4.682-2.72m.94 3.198.001.031c0 .225-.012.447-.037.666A11.944 11.944 0 0 1 12 21c-2.17 0-4.207-.576-5.963-1.584A6.062 6.062 0 0 1 6 18.719m12 0a5.971 5.971 0 0 0-.941-3.197m0 0A5.995 5.995 0 0 0 12 12.75a5.995 5.995 0 0 0-5.058 2.772m0 0a3 3 0 0 0-4.681 2.72 8.986 8.986 0 0 0 3.74.477m.94-3.197a5.971 5.971 0 0 0-.94 3.197M15 6.75a3 3 0 1 1-6 0 3 3 0 0 1 6 0Zm6 3a2.25 2.25 0 1 1-4.5 0 2.25 2.25 0 0 1 4.5 0Zm-13.5 0a2.25 2.25 0 1 1-4.5 0 2.25 2.25 0 0 1 4.5 0Z" />
</svg>

templates/chat/icons/close-icon.html
<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
  <path stroke-linecap="round" stroke-linejoin="round" d="M6 18 18 6M6 6l12 12" />
</svg>

templates/chat/icons/logout-icon.html
<?xml version="1.0" encoding="UTF-8"?><svg width="24px" height="24px" stroke-width="2.1" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" color="#000000"><path d="M12 12H19M19 12L16 15M19 12L16 9" stroke="#000000" stroke-width="2.1" stroke-linecap="round" stroke-linejoin="round"></path><path d="M19 6V5C19 3.89543 18.1046 3 17 3H7C5.89543 3 5 3.89543 5 5V19C5 20.1046 5.89543 21 7 21H17C18.1046 21 19 20.1046 19 19V18" stroke="#000000" stroke-width="2.1" stroke-linecap="round" stroke-linejoin="round"></path></svg>

templates/chat/icons/maginfire-icon.html
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-search absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4" style="color: rgb(34, 37, 37);"><circle cx="11" cy="11" r="8"></circle><path d="m21 21-4.3-4.3"></path></svg>

templates/chat/icons/send-icon.html
<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
  <path stroke-linecap="round" stroke-linejoin="round" d="M6 12 3.269 3.125A59.769 59.769 0 0 1 21.485 12 59.768 59.768 0 0 1 3.27 20.875L5.999 12Zm0 0h7.5" />
</svg>

templates/chat/icons/settings-icon.html
<button data-slot="button" class="inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md text-sm font-medium transition-all disabled:pointer-events-none disabled:opacity-50 [&amp;_svg]:pointer-events-none [&amp;_svg:not([class*='size-'])]:size-4 shrink-0 [&amp;_svg]:shrink-0 outline-none focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px] aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive hover:text-accent-foreground dark:hover:bg-accent/50 size-9 hover:bg-opacity-10" style="color: rgb(35, 35, 35);"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-ellipsis-vertical h-5 w-5"><circle cx="12" cy="12" r="1"></circle><circle cx="12" cy="5" r="1"></circle><circle cx="12" cy="19" r="1"></circle></svg></button>

templates/chat/icons/user-logo.html
{% load chat_extras %}

<span class="relative flex size-8 shrink-0 overflow-hidden rounded-full h-10 w-10">
    <span class="bg-muted flex size-full items-center justify-center rounded-full font-semibold" style="background-color: rgb(7, 128, 128); color: rgb(35, 35, 35);">
        {{ username | userchar }}
    </span>
</span>

templates/chat/index.html
<!-- chat/templates/chat/index.html -->
<!DOCTYPE html>
<html class="h-full">
<head>
    <meta charset="utf-8"/>
    <title>Chat Rooms</title>
    {% load static %}
    <link href="{% static "chat/css/output.css" %}" rel="stylesheet">
</head>
<body>
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}



<div class="flex h-screen bg-[#f8f5f2]">
    <div id="chat-selection" class="w-80 border-r flex flex-col bg-[#ffffff]">
        {% include "chat/room-list-banner.html" %}
        <div id="room-list" class="flex-1 overflow-y-auto">
            {% for room in sorted_rooms %}
                {% include "chat/room-list-item.html" %}
            {% endfor %}
        </div>
    </div>
    <div id="chatroom" class="flex-1 flex flex-col">
        {% include "chat/room.html" %}
    </div>
</div>
<div id="modal-add-friend" class="hidden">
    {% include "friends/add-friend.html" %}
</div>
<script>
    document.querySelectorAll('.room').forEach(roomDiv => {
        roomDiv.addEventListener('click', () => {
        const roomId = roomDiv.dataset.roomId;
        window.location.pathname = '/chat/' + roomId + '/';
        });
    });
</script>
<div id="modal-add-group" class="hidden">
    {% include "chat/create-group-modal.html" %}
</div>
<script>

        const addGroupModal = document.getElementById("modal-add-group");

        const openAddGroupButton = document.getElementById("add-group-open-modal");

        const closeAddGroupButton = document.getElementById("add-group-close-modal");

        openAddGroupButton.addEventListener("click", () => {
            addGroupModal.classList.remove("hidden");
        });

        closeAddGroupButton.addEventListener("click", () => {
            addGroupModal.classList.add("hidden");
        });



document.getElementById("searchRoom").addEventListener("input", function () {
    const filter = this.value.toLowerCase();
    const items = document.querySelectorAll("#room-list .room-list-item");

    items.forEach(item => {
        const text = item.dataset.roomName.toLowerCase();
        if (text.includes(filter)) {
            item.style.display = ""; //show
        } else {
            item.style.display = "none"; // hide
        }
    });
});

</script>
</body>
</html>

templates/chat/received-message.html
<div class="flex justify-start">
    <div class="flex items-end gap-2 max-w-xs lg:max-w-md">
        {% include "chat/icons/user-logo.html" with username=message.sender.username %}
        <div class="bg-card text-card-foreground flex flex-col gap-4 rounded-xl shadow-sm p-3 border bg-white text-[rgb(34,37,37)] border-[rgb(35,35,35)]" >
            <p class="text-sm leading-relaxed">
            {{message.content}}
            </p>
            <p class="text-xs mt-1 opacity-70" style="color: rgb(34, 37, 37);">{{message.timestamp}}</p>
        </div>
    </div>
</div>

templates/chat/room-banner.html
<div id="room-banner" class="flex items-center justify-between p-4 border-b bg-[#ffffff]">
    <div class="flex items-center gap-3">
        {% include "chat/icons/user-logo.html" with username=current_room.name  %}
        <div>
            <h1 class="font-semibold text-lg" style="color: rgb(35, 35, 35);">
                {{ current_room.name }}
            </h1>
        </div>
    </div>
    <div id="room-banner-buttons" class="flex items-center gap-2">
        {% include "chat/icons/settings-icon.html" %}
        <form action="/accounts/logout/" method="post">
        {% csrf_token %}
        <button class="flex items-center gap-2 px-3 h-8 rounded-md border text-sm font-medium text-[#F45D48] border-[#F45D48] hover:bg-[#F45D48] hover:text-white hover:cursor-pointer">
          Logout
        </button>
        </form>
    </div>
</div>

templates/chat/room-list-banner.html
<div class="p-4 border-b border-[#232323]">
  <div class="flex items-center justify-between mb-4">
    <h2 class="text-xl font-semibold text-[#232323]">Chats</h2>

    <div class="flex gap-2">
      <button id="add-friend-open-modal"class="flex items-center justify-center rounded-md h-8 w-8 shadow hover:opacity-90 bg-[#078080] hover:cursor-pointer">
        {% include "chat/icons/add-friend-icon.html"%}
      </button>

      <button id="add-group-open-modal"class="flex items-center justify-center rounded-md h-8 w-8 shadow hover:opacity-90 bg-[#F45D48] hover:cursor-pointer">
        {% include "chat/icons/add-group-icon.html" %}
      </button>
    </div>
  </div>

  <div class="relative">
    {% include "chat/icons/maginfire-icon.html" %}
    <input 
       id="searchRoom"
       class="h-9 w-full rounded-md px-3 pl-10 py-1 border shadow outline-none bg-[#f8f5f2] border-[#232323] text-[#222525]"
       placeholder="Search chats..." />
  </div>
</div>

templates/chat/room-list-item.html
<div class="room-list-item room p-4 border-b cursor-pointer hover:bg-opacity-50 transition-colors bg-opacity-100 hover:bg-[#f8f5f2]" data-room-id='{{room.id}}' data-room-name='{{room.name}}'>
    <div class="flex items-center gap-3">
        <div>
            {% include "chat/icons/user-logo.html" with username=room.name  %}
        </div>
        <div class="flex-1 min-w-0">
            <div class="flex items-center justify-between">
                <h3 class="font-semibold truncate"> {{ room.name }}</h3>
                <span class="text-xs">{{ room.last_message.timestamp|time:"H:i"  }}</span>
            </div>
            <div class="flex items-center justify-between mt-1"> 
                <p class="text-sm truncate">{{ room.last_message.content }}</p> 
            </div>
        </div>
    </div>
</div>

templates/chat/room.html
{% include "chat/room-banner.html" %}

<div id="chat-log" class="flex-1 flex-col overflow-y-auto p-4 space-y-4 bg-[#f8f5f2]">    
    {% for message in latest_messages %}
        {% if message.sender != request.user %}
            {% include "chat/received-message.html" with message=message %}
        {% else %}
            {% include "chat/send-message.html" with message=message %}
        {% endif %}
    {% endfor %}
</div>

<div class="p-4 border-t bg-[#ffffff]">
    <div class="flex items-center gap-2">
        <input id="chat-message-input" type="text" class="w-full flex-1 h-9 rounded-md border px-3 py-1 text-sm outline-none bg-[#f8f5f2] focus:ring-2 focus:ring-primary" placeholder="type a message...">
        <button id="chat-message-submit" class="flex items-center justify-center rounded-md text-sm font-medium bg-[#078080] text-white hover:bg-[#066666] h-9 w-9 disabled:opacity-50">
            {% include "chat/icons/send-icon.html" %}
        </button>
    </div>
</div>
{{ current_room.id|json_script:"room-id" }}
   <script>
    const roomId = JSON.parse(document.getElementById('room-id').textContent);
    const chatSocket = new WebSocket(
        'ws://'
        + window.location.host
        + '/ws/chat/'
        + roomId
        + '/'
    );
    function addMessage(message){
        var messageHtml = "";

        if (message.author == "{{ request.user }}"){
            messageHtml = createSendMessageElement(message);
        }else{
            messageHtml = createReceivedMessage(message);
        }

        const chatLog = document.getElementById("chat-log");
        chatLog.appendChild(messageHtml);
    }
    chatSocket.onmessage = function(e) {
        const data = JSON.parse(e.data);



        const message = {
            content: data.message,
            author: data.user,
            timestamp: getCurrentTime()
        };
        addMessage(message)
    };

    chatSocket.onclose = function(e) {
        console.error('Chat socket closed unexpectedly');
    };

    document.querySelector('#chat-message-input').focus();
    document.querySelector('#chat-message-input').onkeyup = function(e) {
        if (e.key === 'Enter') {  // enter, return
            document.querySelector('#chat-message-submit').click();
        }
    };
    
    //Send message
    document.querySelector('#chat-message-submit').onclick = function(e) {
        const messageInputDom = document.querySelector('#chat-message-input');
        const message = messageInputDom.value;
        chatSocket.send(JSON.stringify({
            'message': message,
        }));
        messageInputDom.value = '';
    };

    function getCurrentTime() {
        const now = new Date();
        const hours = String(now.getHours()).padStart(2, '0');   // np. "09"
        const minutes = String(now.getMinutes()).padStart(2, '0'); // np. "05"
        return `${hours}:${minutes}`;
    }
    function createSendMessageElement(message) {
        const outerDiv = document.createElement("div");
        outerDiv.className = "flex justify-end";

        const innerDiv = document.createElement("div");
        innerDiv.className = "flex flex-col gap-4 rounded-rglg border p-3 shadow-sm text-gray-800 border-gray-800 bg-[#078080]";

        const contentP = document.createElement("p");
        contentP.className = "text-sm";
        contentP.textContent = message.content;

        const timeP = document.createElement("p");
        timeP.className = "text-xs opacity-70";
        timeP.textContent = message.timestamp;

        innerDiv.appendChild(contentP);
        innerDiv.appendChild(timeP);
        outerDiv.appendChild(innerDiv);

        return outerDiv;
    }

    function createReceivedMessageElement(message) {
        const outerDiv = document.createElement("div");
        outerDiv.className = "flex justify-start";

        const innerDiv = document.createElement("div");
        innerDiv.className = "bg-card text-card-foreground flex flex-col gap-4 rounded-xl shadow-sm p-3 border bg-white text-[rgb(34,37,37)] border-[rgb(35,35,35)]";

        const contentP = document.createElement("p");
        contentP.className = "text-sm";
        contentP.textContent = message.content;

        const timeP = document.createElement("p");
        timeP.className = "text-xs mt-1 opacity-70 text-[rgb(34,37,37)]";
        timeP.textContent = message.timestamp;

        innerDiv.appendChild(contentP);
        innerDiv.appendChild(timeP);
        innerDiv.appendChild(createUserAvatar(message.author))
        outerDiv.appendChild(innerDiv);

        return outerDiv;
    }

    function createUserAvatar(username) {
        // główny span
        const outerSpan = document.createElement("span");
        outerSpan.className = "relative flex size-8 shrink-0 overflow-hidden rounded-full h-10 w-10";

        // wewnętrzny span
        const innerSpan = document.createElement("span");
        innerSpan.className = "bg-[rgb(7,128,128)] text-[rgb(35,35,35)] flex size-full items-center justify-center rounded-full font-semibold";

        // pierwsza litera username
        const initial = username.charAt(0).toUpperCase();
        innerSpan.textContent = initial;

        // składanie
        outerSpan.appendChild(innerSpan);

        return outerSpan;
    }
</script>

templates/chat/send-message.html
<div class="flex justify-end">
    <div class="flex flex-col gap-4 rounded-lg border p-3 shadow-sm text-gray-800 border-gray-800 bg-[#078080]">
      <p class="text-sm">{{message.content}}</p>
      <p class="text-xs opacity-70">{{message.timestamp}}</p>
    </div>
</div>

templates/friends/add-friend-record.html
<div class="flex items-center justify-between p-3 rounded-lg border border-[#232323] cursor-pointer transition-colors bg-[#f8f5f2]">
  <div class="flex items-center gap-3">
    <div class="relative">
      <span class="flex h-10 w-10 items-center justify-center rounded-full font-semibold bg-[#078080] text-[#232323]">JD</span>
      <div class="absolute -bottom-1 -right-1 w-3 h-3 rounded-full border-2 border-white bg-[#f45d48]"></div>
    </div>
    <div>
        <p class="font-medium text-[#232323]">{{ username }}</p>
      <!-- <p class="text-xs text-[#222525]">Online</p> -->
    </div>
  </div>
  <button  data-username="{{ username }}" class=" button-add-friend-record h-8 rounded-md px-3 text-sm font-medium bg-[#078080] text-[#232323] hover:bg-primary/90 hover:cursor-pointer">Add Friend</button>
</div>